info:
  version: 1.0.9
  description: AMF configuration

configuration:
  amfName: AMF
  ngapIpList:
    - 10.100.0.30
  ngapPort: 38412
  sbi:
    scheme: http
    registerIPv4: 10.100.0.30
    bindingIPv4: 0.0.0.0
    port: 8000
  serviceNameList:
    - namf-comm
    - namf-evts
    - namf-mt
    - namf-loc
    - namf-oam
  servedGuamiList:
    - plmnId:
        mcc: "999"
        mnc: "70"
      amfId: cafe00
  supportTaiList:
    - plmnId:
        mcc: "999"
        mnc: "70"
      tac: "000001"
  plmnSupportList:
    - plmnId:
        mcc: "999"
        mnc: "70"
      snssaiList:
        - sst: 1
          sd: "000001"
        - sst: 3
          sd: "000002"
  supportDnnList:
    - video
    - iot
  nrfUri: http://10.100.0.20:8000
  security:
    integrityOrder: [NIA2, NIA0]
    cipheringOrder: [NEA0, NEA2]
  networkName:
    full: free5GC
    short: free
  locality: area1
  sctp:
    numOstreams: 3
    maxInstreams: 5
    maxAttempts: 2
    maxInitTimeout: 2
  defaultUECtxReq: false
  t3502Value: 720
  t3512Value: 3240
  non3gppDeregistrationTimerValue: 3240
  t3513:
    enable: true
    expireTime: 6s
    maxRetryTimes: 4
  t3522:
    enable: true
    expireTime: 6s
    maxRetryTimes: 4
  t3550:
    enable: true
    expireTime: 6s
    maxRetryTimes: 4
  t3555:
    enable: true
    expireTime: 6s
    maxRetryTimes: 4
  t3560:
    enable: true
    expireTime: 6s
    maxRetryTimes: 4
  t3565:
    enable: true
    expireTime: 6s
    maxRetryTimes: 4
  t3570:
    enable: true
    expireTime: 6s
    maxRetryTimes: 4

logger:
  enable: true
  level: info
  reportCaller: false
