version: 1.0.3
description: UPF mMTC configuration

pfcp:
  addr: 10.100.0.41
  nodeID: 10.100.0.41
  retransTimeout: 1s
  maxRetrans: 3

gtpu:
  forwarder: gtp5g
  ifList:
    - addr: 10.100.0.41
      type: N3

dnnList:
  - dnn: iot
    cidr: 10.62.0.0/16
    natifname: eth0

logger:
  enable: true
  level: info
  reportCaller: false
